### ISSUE TITLE
missing .cue and some FILE selection

### ISSUE THREAD

**Issue by itsmetoolala** [DmitryVarennikov/cuegenerator-react#19]
Hello and sorry for my bad english.
I am using this: https://cuegenerator.net
Thank you for this great simple program. Thank you!!!

But there are some issues.

1.) Sometimes (I'm in Opera only) forgot cuegenerator.net the ".cue" in the end of file while saving to my desktop or folder.
This is like "untitled" instead of "untitled.cue".
I've rename it and it works great. But I guess it's a bug?

2.) I try to select audiofiles like OGG or OPUS in creating cue sheet. But this is not allowed. I have to re-edit the cue sheet on my desktop. (Ex: >FILE "" MP3< to >FILE "" OGG< or to >FILE "" OPUS<

I don't know if it's necessary (FILE) but I guess I as a user should be able to define on my own which file I want to use. ;-)

Thank you very much!

**Comment by DmitryVarennikov** [comment]
Hi @itsmetoolala,

Thanks for reporting the issues. Let's take them apart separately. 

1. Cue file suggested name is taken directly from the "File name" input. I see you mentioned Opera which is a non-standard browser. Can you reproduce this issue in other browsers like Google Chrome or Safari / Edge? Also make sure your OS shows file extensions. 
2. I guess what you're saying is that the provided set of values inside the "File type" select input is insufficient as you would like to use non-declared options like `OGG` or `OPUS`. This request makes sense. There is no practical limitation to the file types from the business perspective. The way file type options are represented is the old dropdown input. In this case we can make the file type input an arbitrary text with a predefined "MP3" value as it's the most popular option. 

Let me know if you have any questions or suggestions.

**Comment by itsmetoolala** [comment]
Hello Dmitry Varennikov and thank you very much for answering me!

In the meantime I've read a lot more about cue sheets and their "behavior" or rather, "how to edit them properly".
Well, I now know that after the line "FILE" there must be WAVE or MP3.
(i.ex. "trackname.wav" WAVE or "trackname.mp3" MP3 or for every other files like this "trackname.opus" WAVE)

Allegedly, other statements would not be correct and could allegedly not be correctly recognized. But I am not familiar with it. Please bear with me.
Personally, I only use AIMP and the program doesn't really care what is written to begin in the cue sheet. The main thing is that the tracks match the times and the songs are neatly separated in the file. Curios!
So much for that.
So, I apologize, as I now know that I have to specify "WAVE" for .ogg or .opus.
I read everything else so far on the Internet for hours, and as I said, I now know a little more.

About the "problem" with the occasional missing .cue at the end of the file, I cannot reproduce, which is why I trust your skills.
Sometimes, when I click download too fast, change something again, download again, change something again and then download again, it happens that the ".cue" is missing at the end of the file.
Otherwise everything works fine.

Unfortunately I only use Opera, which is based on Chrome. Sure, Opera is different in behavior, but I think it can't really be because of that.

**- OH and.... I have one tiny _SUGGESTION_ -**
 
I look up for the track list on YT because I was downloading the sound file and people often forget the "0" (zero) preceding the first few tracks. So something like "Track 1" 0:00, "Track 2" 2:04 and then, for example, "Track 3" at 13:35.
The cue sheet does not work because the leading zero in the first tracks is missing.
Correctly would be: 00:00, then 02:04 and (then normal) 13:35.
_Perhaps it is still conceivable that your program could arrange to simply add a leading zero to the missing leading zero?_
This would be really cool!!!

Because sometimes I forget that too and then I wonder why the track always starts all over again when I click on a part of it.
*laugh*

But I am delighted to have found such a great and wonderfully easy-to-use program like yours!
Thank you very much for this and please stay in good health! ;-)

**Comment by itsmetoolala** [comment]
AH! I GOT IT!
Problem known!
The ".cue" ending depends on what is going on in the field "File name:"!!!!!
If you leave it blank, it will download as untitled.cue!
If you fill it correctly with filename (like it should be), it will create the filename with as example .wav or .mp3 or whatever
Please see my pictures!
This here works because "File name:" is blank:
![works1](https://user-images.githubusercontent.com/81344443/112671130-17abb400-8e62-11eb-955f-c53c0b8b0252.png)
![works1a](https://user-images.githubusercontent.com/81344443/112671187-2a25ed80-8e62-11eb-8879-8ea084c2114a.png)

This is NOT working, because I fill in the title correctly:
![works not1](https://user-images.githubusercontent.com/81344443/112671262-41fd7180-8e62-11eb-8bfb-c069a7793762.png)

And this is not working because I left the ending (.wav)
![works not2](https://user-images.githubusercontent.com/81344443/112671452-78d38780-8e62-11eb-889c-f523c6488a9e.png)

So, as you can see, I found it out just now (accidentally).
Please let me know if it works for you, too.
Thank you very much!

**Comment by DmitryVarennikov** [comment]
Yes indeed, the result cue file name depends on the sound file name (mp3, etc). I made a fix so the result cue file name is either
- "**sound file name.cue**"
- or just "**Untitled.cue**" when no file name input is given

**Comment by DmitryVarennikov** [comment]
Regarding additional file types that are not on the list. I see you found a way around it

> So, I apologize, as I now know that I have to specify "WAVE" for .ogg or .opus.

I'll close the current issue

**Comment by itsmetoolala** [comment]
> Yes indeed, the result cue file name depends on the sound file name (mp3, etc). I made a fix so the result cue file name is either
> 
> * "**sound file name.cue**"
> * or just "**Untitled.cue**" when no file name input is given

This is sooo perfect. Thank you very much!!!
