### ISSUE TITLE
Parse time in track list without leading zero for minutes

### ISSUE THREAD

**Issue by itsmetoolala** [DmitryVarennikov/cuegenerator-react#20]
Hello!
I hope it is ok to post inhere? I'm new here to Github, so please bear with me.

I have one tiny Suggestion!
 
I look up for track list on YT because I was downloading the sound file and people often forget the "0" (zero) preceding the first few tracks. So something like "Track 1" 0:00, "Track 2" 2:04 and then, for example, "Track 3" at 13:35.
The cue sheet does not work because the leading zero in the first tracks is missing.
Correctly would be: 00:00, then 02:04 and (then normal) 13:35.

Perhaps it is still conceivable that your program could arrange to simply add a leading zero to the missing leading zero?

This would be really cool!!!

Because sometimes I forget that too and then I wonder why the track always starts all over again when I click on a part of it. ;-)

Thank you very much!!!

PS: I really don't know to find the Github section about "suggestions" or similar. Where can I find such a forum for this program?

**Comment by DmitryVarennikov** [comment]
While parsing track list handle minutes without leading zero, so that `1:23` is parsed as 1 minute, 23 seconds. Once the time is parsed correctly format it by adding missing leading zero while compiling the result cue output.

**Comment by DmitryVarennikov** [comment]
I released support for the following format:

In the track list field:
```
0:01 p1 - t1
1:12 p2 - t2
9:34 p3 - t3
10:45: p4 - t4
```

The result cue output 
```
  TRACK 01 AUDIO
    PERFORMER "p1"
    TITLE "t1"
    INDEX 00 00:00:00
    INDEX 01 00:01:00
  TRACK 02 AUDIO
    PERFORMER "p2"
    TITLE "t2"
    INDEX 01 01:12:00
  TRACK 03 AUDIO
    PERFORMER "p3"
    TITLE "t3"
    INDEX 01 09:34:00
  TRACK 04 AUDIO
    PERFORMER ": p4"
    TITLE "t4"
    INDEX 01 10:45:00
```

Check it yourself at https://cuegenerator.net/ @itsmetoolala

**Comment by itsmetoolala** [comment]
Thank you veryyyy muuuch! Now it is all perfect! Thank you sooo much!♥
