### ISSUE TITLE
add rem parameter

### ISSUE THREAD

**Issue by Aliaksandr3by** [DmitryVarennikov/cuegenerator-react#22]
I always use a REM data for to add an addition information.
I think that will be good idea to add the "time_name" format: for exemple "09:21 Pen Cap Chew "
Thx for your work.

```
REM ALBUM ARTIST "Nirvana"
REM GENRE Grunge
REM DATE 1988
REM COMMENT upcast
PERFORMER "Nirvana"
REM REPLAYGAIN_ALBUM_GAIN -6.05 dB
REM REPLAYGAIN_ALBUM_PEAK 1.002813
TITLE "January 3rd, 1988, Crover residence, Aberdeen, WA"
FILE "Nirvana practice January 3rd 1988.mp4" MP3
```
![image](https://user-images.githubusercontent.com/11432724/114196282-e4851c80-9959-11eb-87f4-2528b9444a4f.png)

**Comment by DmitryVarennikov** [comment]
There are [a few different ways](https://github.com/DmitryVarennikov/cuegenerator-react/blob/main/src/Cue/Parser.test.ts#L98) to recognize and separate time from a performer. This feature is added for convenience and laziness, i.e. if you want to chop a long track quickly and dirty. Once (and if) the time is recognized it's written down to the end cue file. 

I'm trying to understand how it could be useful to know the original track list time format once the resulted cue file is produced? Also given the complication there are multiple formats?
