### ISSUE TITLE
 autoreplace \" on \'

### ISSUE THREAD

**Issue by Aliaksandr3by** [DmitryVarennikov/cuegenerator-react#23]
it simple deletes the double quotes "
it would be better if it replace it

**Comment by DmitryVarennikov** [comment]
Hi @Aliaksandr3by,

Could you please elaborate on where exactly double quotes are deleted? Please provide an input and the expected result. 

Thanks

**Comment by Aliaksandr3by** [comment]
![image](https://user-images.githubusercontent.com/11432724/116577597-49a8ae00-a919-11eb-827b-54b8d8fa7630.png)

**Comment by DmitryVarennikov** [comment]
Cue sheet syntax is defined by the CDRWIN Users Manual, but it doesn't mention escaping quotation marks, so the decision is left to implementers. In order to unify the display process I agree to replace double quotes with single quotes. 

The change has been deployed.
