### ISSUE TITLE
[bug] the app create a new, redundant line

### ISSUE THREAD

**Issue by Aliaksandr3by** [DmitryVarennikov/cuegenerator-react#26]
![image](https://user-images.githubusercontent.com/11432724/116778396-4b3db780-aa7a-11eb-9003-00720f880764.png)

**Comment by DmitryVarennikov** [comment]
**Bug**

When first track does **not** start at `00:00:00` the app adds a pre-gap in the form of the `INDEX 00` and time pointing to the very beginning `00:00:00`. 

In this case Parser doesn't cast parsed time correctly, so the first track time `00:00:00` becomes `0:00:00` which leads to this misbehaviour.

**Comment by DmitryVarennikov** [comment]
Fixed and deployed
