### ISSUE TITLE
add recognize for the  title-time invert example

### ISSUE THREAD

**Issue by Aliaksandr3by** [DmitryVarennikov/cuegenerator-react#28]
auto recognize for 

Song list:
School 1:42
Floyd The Barber 4:20
Love Buzz 6:45

I use for that Npp with regex:
`^(.*)\s+(\d{1,2}(?:\:\d{1,2})+)`
and replace with `$2 $1`

**Comment by DmitryVarennikov** [comment]
Thanks for creating the issue. I may look at it one I have time. If you're interested in expediting it you can create a PR

**Comment by DmitryVarennikov** [comment]
Done

<img width="872" alt="Screenshot 2023-04-16 at 11 04 46 PM" src="https://user-images.githubusercontent.com/457097/232383430-7eeb8633-f681-4615-8d18-698c45bdf097.png">
