### ISSUE TITLE
to add a message of error when it has a negative time

### ISSUE THREAD

**Issue by Aliaksandr3by** [DmitryVarennikov/cuegenerator-react#29]
![image](https://user-images.githubusercontent.com/11432724/131251758-8878d4a9-58f1-4c83-a0b3-91b82b1e3fa9.png)

**Comment by DmitryVarennikov** [comment]
Hi and thanks for reporting an issue. 

What does have a negative time in your example?

**Comment by Aliaksandr3by** [comment]
cue don't 'work?
i think it is a good idea if I get a message of time error.?

**Comment by DmitryVarennikov** [comment]
> cue don't 'work?

What exactly doesn't work?

**Comment by Aliaksandr3by** [comment]
![image](https://user-images.githubusercontent.com/11432724/131391018-db0d75a3-79b9-486c-a089-968b35934cd0.png)

![image](https://user-images.githubusercontent.com/11432724/131390966-dc01dd1b-9c80-488d-bed1-a24e4027a4c3.png)

**Comment by DmitryVarennikov** [comment]
ok I see the issue now. This is the expected behavior as the cue-generator does NOT validate the resulted cue for semantic errors.
