### ISSUE TITLE
Ability to add large file with timestamps and titles together and convert to cuesheet

### ISSUE THREAD

**Issue by eltonfreak** [DmitryVarennikov/cuegenerator-react#31]
Would it be possible to add a file like the following:
00:00:00
 track 1
00:03:10
track 2
00:06:45
track 3
ETC...
and convert it into:
track 1 audio
title track 1
ETC...
this would be useful as I have a large mp3 file which is several hours long and has 125 diferent timestamps spesified
thank You in advance.
Regards:
Melissa.

**Comment by DmitryVarennikov** [comment]
Hi Melissa,

I'm not exactly sure how it fits the concept of Cuegenerator service. Can you please explain?
