### ISSUE TITLE
Filenames with accented letters

### ISSUE THREAD

**Issue by freggal** [DmitryVarennikov/cuegenerator-react#34]
Hey, Dmitry

Thanks for this useful prog. Found one small issue - if the filename includes letters with accents, for example "Café", the generated cue file isn't read correctly, at least not by Winamp which is what I test with. Found this today, and after renaming to "cafe" it came good.

**Comment by DmitryVarennikov** [comment]
it could be a file encoding issue, however here's what I did trying to reproduce the it.
I pasted _Café_ into the tracklist then saved the resulted cue file and checked the encoding with `file -I` -- it says `text/plain; charset=utf-8`

I'm not exactly sure why Winamp doesn't like it.
