### ISSUE TITLE
timings are not generating

### ISSUE THREAD

**Issue by Hoerschel** [DmitryVarennikov/cuegenerator-react#35]
I've attempted to use Cue Generator per the exemplars provided with Adobe Audition; however, the marker timings do not populate on the right hand side of the page after they are copied and pasted in the timing section per your instructions. This requires me to manually edit the information in the text document after it is generated. Defeats the who purpose for using this program as it adds extra work.

**Comment by DmitryVarennikov** [comment]
Hello and thanks for your issue. Would you mind providing the timings?

**Comment by Hoerschel** [comment]
I followed the exact procedure you demonstrated under Audition and the timings do not update on the right side of the page.
Marker 01           0:00.000
Marker 02           0:05.992
Marker 03           0:13.775
Marker 04           0:22.687
Marker 05           0:31.520

I wonder if  the tutorial should have included the duration of each marker as it does in the Audacity demo?
Thanks for clarifying.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by DmitryVarennikov** [comment]
I don't have the Adobe Audition at hand to play with markers but reading the [Working with markers](https://helpx.adobe.com/audition/using/markers.html) page says

> In Adobe Audition, a marker can be either a point or a range. A point refers to a specific time position within a waveform (for instance, 1:08.566 from the start of the file). A range has both a start time and an end time (for example, all of the waveform from 1:08.566 to 3:07.379). 

So looking at your markers it seems that you provide only a specific position rather than a range.

**Comment by Hoerschel** [comment]
Yes, the demo your program provided lacks what you have described. I have tried importing a range as you mentioned but it still fails to populate correctly.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by DmitryVarennikov** [comment]
Share the range timings

**Comment by Hoerschel** [comment]
0:00.000              0:10.623
0:10.623              0:21.558
0:21.558              0:31.053



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by DmitryVarennikov** [comment]
Try now with the original timings (point), here's an example 

<img width="739" alt="Screenshot 2023-04-16 at 10 35 01 PM" src="https://user-images.githubusercontent.com/457097/232379243-eaa598f9-e8eb-4008-8498-4c6fd5da7458.png">

**Comment by Hoerschel** [comment]
Yes! Nicely done.
I much prefer working with Audition and CueGenerator because it requires fewer steps than Audacity. Thank you, sir, for working through this issue. Very pleased. This is a great tool.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
