### ISSUE TITLE
unable to creat cuesheet with standard youtube timestamps

### ISSUE THREAD

**Issue by eltonfreak** [DmitryVarennikov/cuegenerator-react#37]
Hello,
load the following in to the website:

expected behaveour:
Performer:
Luke Faulkner
Title:
Chopin Complete Nocturnes
File name:
Chopin Complete Nocturnes (Luke Faulkner).mp3
File type:
MP3
Tracklist:
Nocturnes, Op. 9; No. 1, in B flat Minor. Larghetto
Nocturnes, Op. 9; No. 2, in E flat Major. Andante
Nocturnes, Op. 9; No. 3, in B Major. Allegretto
Nocturnes, Op. 15; No. 1, in F Major. Andante cantabile
Nocturnes, Op. 15; No. 2, in F sharp Major. Larghetto
Nocturnes, Op. 15; No. 3, in G Minor. Lento
Nocturnes, Op. 27; No. 1, in C sharp Minor. Larghetto
Nocturnes, Op. 27; No. 2, in D flat Major. Lento sostenuto
Nocturnes, Op. 32; No. 1, in B Major. Andante sostenuto
Nocturnes, Op. 32; No. 2, in A flat Major. Lento
Nocturnes, Op. 37; No. 1, in G Minor. Andante sostenuto
Nocturnes, Op. 37; No. 2, in G Major. Andantino
Nocturnes, Op. 48; No. 1, in C Minor. Lento
Nocturnes, Op. 48; No. 2, in F sharp Minor. Andantino
Nocturnes, Op. 55; No. 1, in F Minor. Andante
Nocturnes, Op. 55; No. 2, in E flat Major. Lento sostenuto
Nocturnes, Op. 62; No. 1 in B Major. Andante
Nocturnes, Op. 62; No. 2, in E Major. Lento
Nocturne, in E Minor, Op. Posth. 72, No. 1
Nocturne, in C sharp Minor, Op. posth., B. 49. Lento con gran espressione
Nocturne, in C Minor, Op. posth., B. 108. Andante sostenuto
Timings: 
Help
0:00:00
0:05:47
0:10:26
0:17:07
0:21:52
0:25:28
0:30:43
0:36:01
0:41:23
0:46:31
0:51:53
0:59:02
1:05:45
1:12:00
1:19:38
1:24:50
1:29:57
1:37:28
1:43:02
1:47:10
1:51:06
PERFORMER "Luke Faulkner"
TITLE "Chopin Complete Nocturnes"
FILE "Chopin Complete Nocturnes (Luke Faulkner).mp3" MP3
  TRACK 01 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 9; No. 1, in B flat Minor. Larghetto"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 9; No. 2, in E flat Major. Andante"
    INDEX 01 00:00:00
  TRACK 03 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 9; No. 3, in B Major. Allegretto"
    INDEX 01 00:00:00
  TRACK 04 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 15; No. 1, in F Major. Andante cantabile"
    INDEX 01 00:00:00
  TRACK 05 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 15; No. 2, in F sharp Major. Larghetto"
    INDEX 01 00:00:00
  TRACK 06 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 15; No. 3, in G Minor. Lento"
    INDEX 01 00:00:00
  TRACK 07 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 27; No. 1, in C sharp Minor. Larghetto"
    INDEX 01 00:00:00
  TRACK 08 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 27; No. 2, in D flat Major. Lento sostenuto"
    INDEX 01 00:00:00
  TRACK 09 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 32; No. 1, in B Major. Andante sostenuto"
    INDEX 01 00:00:00
  TRACK 10 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 32; No. 2, in A flat Major. Lento"
    INDEX 01 00:00:00
  TRACK 11 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 37; No. 1, in G Minor. Andante sostenuto"
    INDEX 01 00:00:00
  TRACK 12 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 37; No. 2, in G Major. Andantino"
    INDEX 01 00:00:00
  TRACK 13 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 48; No. 1, in C Minor. Lento"
    INDEX 01 00:00:00
  TRACK 14 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 48; No. 2, in F sharp Minor. Andantino"
    INDEX 01 00:00:00
  TRACK 15 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 55; No. 1, in F Minor. Andante"
    INDEX 01 00:00:00
  TRACK 16 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 55; No. 2, in E flat Major. Lento sostenuto"
    INDEX 01 00:00:00
  TRACK 17 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 62; No. 1 in B Major. Andante"
    INDEX 01 00:00:00
  TRACK 18 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturnes, Op. 62; No. 2, in E Major. Lento"
    INDEX 01 00:00:00
  TRACK 19 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturne, in E Minor, Op. Posth. 72, No. 1"
    INDEX 01 00:00:00
  TRACK 20 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturne, in C sharp Minor, Op. posth., B. 49. Lento con gran espressione"
    INDEX 01 00:00:00
  TRACK 21 AUDIO
    PERFORMER "Luke Faulkner"
    TITLE "Nocturne, in C Minor, Op. posth., B. 108. Andante sostenuto"
    INDEX 01 00:00:00

create a valid cuesheet
Note: until recently (8 or 9 weeks) this was working perfectly as expected

**Comment by DmitryVarennikov** [comment]
Tbh, I doubt it ever worked with the standard youtube timings but it's really easy to support. I just hope it won't break anything else. 

The fix has been deployed. Check out https://cuegenerator.net/
